name: Build SunamoAzureDevOpsApi

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoAzureDevOpsApi
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoAzureDevOpsApi/SunamoAzureDevOpsApi.csproj

    - name: Build
      run: dotnet build SunamoAzureDevOpsApi/SunamoAzureDevOpsApi.csproj --configuration Release --no-restore

  test:
    name: Test SunamoAzureDevOpsApi.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoAzureDevOpsApi.Tests/SunamoAzureDevOpsApi.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoAzureDevOpsApi.Tests/SunamoAzureDevOpsApi.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoAzureDevOpsApi.Tests/SunamoAzureDevOpsApi.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
